## Phase 1: Data Collection & Infrastructure

The first stage of this project focuses on acquiring, organizing, and preparing reliable financial data from the Nairobi Securities Exchange (NSE). A robust data foundation is essential for any predictive analytics system, as the quality and structure of the dataset directly influence the reliability of downstream analysis and forecasting models.

For this project, historical NSE stock market data was sourced from publicly available datasets covering multiple years of trading activity. The datasets include key market variables such as trading date, stock code, company name, daily price information, and trading volume. These datasets were downloaded as CSV files and stored within the project directory for processing.

Using Python and the pandas library, the datasets were programmatically loaded and consolidated into a single structured DataFrame. During this step, several preprocessing tasks were performed to ensure consistency across files, including standardizing column names, handling inconsistent formats, and converting the trading date column into a proper datetime format (`%d-%b-%y`). This step ensures that the dataset can be used effectively for time series analysis.

Once the data was successfully integrated, the focus shifted to identifying relevant securities for analysis. Two of the most actively traded and economically significant stocks on the NSE were selected:

- **Safaricom PLC (SCOM)**
- **KCB Group PLC (KCB)**

These stocks provide an excellent case study due to their liquidity, market relevance, and availability of historical trading records.

The output of this phase is a clean, consolidated dataset containing NSE trading data, which will serve as the foundation for subsequent stages of the project, including exploratory data analysis (EDA), feature engineering, predictive modeling, and the development of an interactive forecasting dashboard.

In [1]:
import pandas as pd
import glob
import os

In [2]:
# Path to our CSVs
csv_folder = r"C:\Users\Win\NSE Project\Data" 
all_files = glob.glob(os.path.join(csv_folder, "NSE_data_all_stocks_*.csv"))

In [3]:
# Check columns in the first file
df = pd.read_csv(all_files[1])
print(df.columns)

Index(['DATE', 'CODE', 'NAME', '12m Low', '12m High', 'Day Low', 'Day High',
       'Day Price', 'Previous', 'Change', 'Change%', 'Volume', 'Adjust'],
      dtype='str')

In [4]:

df_list = []
for file in all_files:
    df = pd.read_csv(file)
    df.columns = df.columns.str.strip()  # remove any extra spaces
    
    # Convert DATE with explicit format
    df['DATE'] = pd.to_datetime(df['DATE'], format='%d-%b-%y', errors='coerce')
    
    df_list.append(df)

# Merge all CSVs into a single DataFrame
nse_data = pd.concat(df_list, ignore_index=True)

In [5]:
nse_data.head()

,DATE,CODE,NAME,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjust
0,2013-01-02,EGAD,Eaagads Ltd,8.2,14,25,25,25,25,-,-,-,-
1,2013-01-02,KUKZ,Kakuzi Plc,300,423.5,67.5,67.5,67.5,72,-4.5,6.25%,300,-
2,2013-01-02,KAPC,Kapchorua Tea Kenya Plc,59,95,118,118,118,118,-,-,-,59
3,2013-01-02,LIMT,Limuru Tea Plc,385,475,430,430,430,430,-,-,-,215
4,2013-01-02,SASN,Sasini Plc,14.8,19.6,11.7,12.05,11.9,11.7,0.2,1.71%,"14,500",-

In [6]:
nse_data.tail()

,DATE,CODE,NAME,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjust
204382,2024-12-31,^N25I,NSE 25-Share Index,2364.29,"3,457.87","3,402.80","3,402.80","3,402.80","3,380.24",22.56,0.67%,-,-
204383,2024-12-31,^NASI,NSE All-Share Index,90.1,125.34,123.48,123.48,123.48,123.12,0.36,0.29%,-,-
204384,2024-12-31,^NBDI,NSE Bonds Index,986.46,"1,108.71","1,107.41","1,107.41","1,107.41","1,093.87",13.54,1.24%,-,-
204385,2024-12-31,^ZKEQTK,Zamara Kenya Equity Index (KES),1535.23,"2,547.58","2,519.80","2,519.80","2,519.80","2,495.28",24.52,0.98%,-,-
204386,2024-12-31,^ZKEQTU,Zamara Kenya Equity Index (USD),818.46,"1,697.07","1,677.27","1,677.27","1,677.27","1,662.24",15.03,0.90%,-,-

In [7]:
#lets see the shape iof pour dataset
nse_data.shape

(204387, 13)

In [8]:
nse_data["CODE"].unique()

<StringArray>
[   'EGAD',    'KUKZ',    'KAPC',    'LIMT',    'SASN',     'WTK',    'CGEN',
    'ABSA',    'COOP',     'DTK',    'EQTY',    'HFCK',     'KCB',     'NBK',
    'NCBA',    'SBIC',    'SCBK',    'EVRD',    'XPRS',      'KQ',     'LKL',
     'NMG',    'SMER',     'SGL',    'TPSE',    'UCHM',    'SCAN',     'ARM',
    'BAMB',    'CRWN',    'CABL',    'PORT',    'KENO',    'KEGN', 'KPLC-P4',
 'KPLC-P7',    'KPLC',    'TOTL',    'BRIT',     'CIC',     'JUB',    'KNRE',
    'LBTY',    'SLAM',    'CTUM',     'OCH',     'TCL',     'BOC',     'BAT',
    'CARB',    'EABL',    'ORCH',     'MSC',    'UNGA',    'SCOM',  '^FNK15',
  '^FNK25',   '^N20I',   '^NASI',     'IMH',    'HAFR',    'UMME',     'NSE',
    'FTGH',    'KURV',       nan,   '^N25I',    'FAHR',     'NBV',    'DCON',
     'GLD', '^ZKEQTK', '^ZKEQTU',     'BKG',     'HBE',    'LAPR',   '^N10I',
   '^NBDI',  'HFCK-R']
Length: 79, dtype: str

In [18]:
# we save the consolidated data to our project folder
# we make sure 'data' folder exists
os.makedirs("data", exist_ok=True)

# we save our dataset to the 'data' folder
nse_data.to_csv(r"C:\Users\Win\NSE Project\Data\2013 to 2024 cosolidated all stocks nse_data.csv", index=False)

In [19]:
# now we filter our SCOM and KCB CODE (tickers)
#for safaricom
scom=nse_data[nse_data["CODE"]== "SCOM"].sort_values("DATE")
kcb=nse_data[nse_data["CODE"]=="KCB"].sort_values("DATE")

In [20]:
scom.head()

,DATE,CODE,NAME,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjust
54,2013-01-02,SCOM,Safaricom Plc,23.5,33.5,5,5.15,5.1,5,0.1,2.00%,"3,320,600",-
113,2013-01-03,SCOM,Safaricom Plc,23.5,33.5,5.1,5.25,5.15,5.1,0.05,0.98%,"7,252,500",-
172,2013-01-04,SCOM,Safaricom Plc,23.5,33.5,5.15,5.35,5.25,5.15,0.1,1.94%,"4,125,900",-
231,2013-01-07,SCOM,Safaricom Plc,23.5,33.5,5.2,5.45,5.35,5.25,0.1,1.90%,"4,098,600",-
290,2013-01-08,SCOM,Safaricom Plc,23.5,33.5,5.4,5.85,5.6,5.35,0.25,4.67%,"10,998,900",-

In [22]:
# we save our safaricom consolidated data
scom.to_csv(r"C:\Users\Win\NSE Project\Data\2013 to 2024 cosolidated safaricom stocks nse_data.csv", index=False)

In [23]:
kcb.head()

,DATE,CODE,NAME,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjust
12,2013-01-02,KCB,KCB Group Plc,33.75,55.5,30,30.5,30.25,29.75,0.5,1.68%,"144,500",-
71,2013-01-03,KCB,KCB Group Plc,33.75,55.5,30.25,31.5,31,30.25,0.75,2.48%,"790,400",-
130,2013-01-04,KCB,KCB Group Plc,33.75,55.5,31,31.5,31,31,-,-,"5,264,700",-
189,2013-01-07,KCB,KCB Group Plc,33.75,55.5,30.25,31.5,31,31,-,-,"2,037,700",-
248,2013-01-08,KCB,KCB Group Plc,33.75,55.5,30.25,31.25,31,31,-,-,"637,600",-

In [24]:
#we save our consolidated KCB data
kcb.to_csv(r"C:\Users\Win\NSE Project\Data\2013 to 2024 cosolidated KCB stocks nse_data.csv", index=False)

In [25]:
#we reset the indices
scom.reset_index(drop=True,inplace=True)
kcb.reset_index(drop=True,inplace=True)

In [26]:
scom.head(2)

,DATE,CODE,NAME,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjust
0,2013-01-02,SCOM,Safaricom Plc,23.5,33.5,5,5.15,5.1,5,0.1,2.00%,"3,320,600",-
1,2013-01-03,SCOM,Safaricom Plc,23.5,33.5,5.1,5.25,5.15,5.1,0.05,0.98%,"7,252,500",-

In [27]:
kcb.head(2)

,DATE,CODE,NAME,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjust
0,2013-01-02,KCB,KCB Group Plc,33.75,55.5,30,30.5,30.25,29.75,0.5,1.68%,"144,500",-
1,2013-01-03,KCB,KCB Group Plc,33.75,55.5,30.25,31.5,31,30.25,0.75,2.48%,"790,400",-

In [28]:
len(scom)

2981

In [29]:
len(kcb)

2981

In [30]:
print(f"Safaricom data shape is: {scom.shape}")
print(f"KCB shape is: {kcb.shape}")

Safaricom data shape is: (2981, 13)
KCB shape is: (2981, 13)

In [31]:
#lets check for null values in the safaricom data
scom.isnull().sum()

DATE         0
CODE         0
NAME         0
12m Low      0
12m High     0
Day Low      0
Day High     0
Day Price    0
Previous     0
Change       0
Change%      0
Volume       0
Adjust       0
dtype: int64

In [32]:
#lets check for null values in the kcb data
kcb.isnull().sum()

DATE         0
CODE         0
NAME         0
12m Low      0
12m High     0
Day Low      0
Day High     0
Day Price    0
Previous     0
Change       0
Change%      0
Volume       0
Adjust       0
dtype: int64

In [33]:
# lets see what type of data we have
scom.info()

<class 'pandas.DataFrame'>
RangeIndex: 2981 entries, 0 to 2980
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   DATE       2981 non-null   datetime64[us]
 1   CODE       2981 non-null   str
 2   NAME       2981 non-null   str
 3   12m Low    2981 non-null   str
 4   12m High   2981 non-null   str
 5   Day Low    2981 non-null   str
 6   Day High   2981 non-null   str
 7   Day Price  2981 non-null   str
 8   Previous   2981 non-null   str
 9   Change     2981 non-null   str
 10  Change%    2981 non-null   str
 11  Volume     2981 non-null   str
 12  Adjust     2981 non-null   str
dtypes: datetime64[us](1), str(12)
memory usage: 302.9 KB

In [34]:
#we check for duplicates in the safaricom data
scom.duplicated().sum()

np.int64(1)

In [35]:
#we check for duplicates in the kcb data
kcb.duplicated().sum()

np.int64(1)

In [36]:
#we found one duplicate, and we opt to drop it
scom.drop_duplicates(inplace=True)
scom.duplicated().sum()

np.int64(0)

In [37]:
#we found one duplicate and we opt to drop it
kcb.drop_duplicates(inplace=True)
kcb.duplicated().sum()

np.int64(0)

In [38]:
scom.columns

Index(['DATE', 'CODE', 'NAME', '12m Low', '12m High', 'Day Low', 'Day High',
       'Day Price', 'Previous', 'Change', 'Change%', 'Volume', 'Adjust'],
      dtype='str')

In [43]:
# 1. Remove the '%' symbol
# 2. Replace the dash '-' (used for no change) with '0'
# 3. Remove commas (if any)
scom['Change%'] = scom['Change%'].astype(str).str.replace('%', '', regex=False)
scom['Change%'] = scom['Change%'].replace('-', '0').str.replace(',', '', regex=False)
scom['Change'] = scom['Change'].replace('-', '0').str.replace(',', '', regex=False)

# 4. Now convert to float safely
scom['Change%'] = pd.to_numeric(scom['Change%'], errors='coerce')
scom['Change'] = pd.to_numeric(scom['Change'], errors='coerce')

# 5. Convert to decimal (0.02 becomes 0.0002) for mathematical modeling
scom['Change%'] = scom['Change%'] / 100

In [44]:
# 1. Remove the '%' symbol
# 2. Replace the dash '-' (used for no change) with '0'
# 3. Remove commas (if any)
kcb['Change%'] = kcb['Change%'].astype(str).str.replace('%', '', regex=False)
kcb['Change%'] = kcb['Change%'].replace('-', '0').str.replace(',', '', regex=False)
kcb['Change'] = kcb['Change'].replace('-', '0').str.replace(',', '', regex=False)
# 4. Now convert to float safely
kcb['Change%'] = pd.to_numeric(scom['Change%'], errors='coerce')
kcb['Change'] = pd.to_numeric(scom['Change'], errors='coerce')

# 5. Convert to decimal (0.02 becomes 0.0002) for mathematical modeling
kcb['Change%'] = scom['Change%'] / 100

In [ ]:
# we now convert the datatypes to the correct ones
#for safaricom data:
cols=[ '12m Low', '12m High', 'Day Low', 'Day High','Day Price', 'Previous', 'Volume', 'Adjust']
for c in cols:
    scom[c]=pd.to_numeric(scom[c].str.replace(',',''),errors= 'coerce')

In [46]:
scom.info()

<class 'pandas.DataFrame'>
Index: 2980 entries, 0 to 2980
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   DATE       2980 non-null   datetime64[us]
 1   CODE       2980 non-null   str
 2   NAME       2980 non-null   str
 3   12m Low    2980 non-null   float64
 4   12m High   2980 non-null   float64
 5   Day Low    2980 non-null   float64
 6   Day High   2980 non-null   float64
 7   Day Price  2980 non-null   float64
 8   Previous   2980 non-null   float64
 9   Change     2980 non-null   float64
 10  Change%    2980 non-null   float64
 11  Volume     2980 non-null   float64
 12  Adjust     0 non-null      float64
dtypes: datetime64[us](1), float64(10), str(2)
memory usage: 325.9 KB

In [68]:
#we drop the adjust column
scom_cleaned= scom.drop(columns=["Adjust"])

In [69]:
#we save our cleaned Safaricom data
scom_cleaned.to_csv(r"C:\Users\Win\NSE Project\Data\2013 to 2024 CLEANED_cosolidated_SAFARICOM_stocks nse_data.csv", index=False)

In [48]:
#for KCB data:
cols=[ '12m Low', '12m High', 'Day Low', 'Day High','Day Price', 'Previous', 'Volume', 'Adjust']
for c in cols:
    kcb[c]=pd.to_numeric(kcb[c].str.replace(',',''),errors= 'coerce')

In [49]:
kcb.info()

<class 'pandas.DataFrame'>
Index: 2980 entries, 0 to 2980
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   DATE       2980 non-null   datetime64[us]
 1   CODE       2980 non-null   str
 2   NAME       2980 non-null   str
 3   12m Low    2980 non-null   float64
 4   12m High   2980 non-null   float64
 5   Day Low    2980 non-null   float64
 6   Day High   2980 non-null   float64
 7   Day Price  2980 non-null   float64
 8   Previous   2980 non-null   float64
 9   Change     2980 non-null   float64
 10  Change%    2980 non-null   float64
 11  Volume     2980 non-null   float64
 12  Adjust     0 non-null      float64
dtypes: datetime64[us](1), float64(10), str(2)
memory usage: 325.9 KB

In [61]:
#we drop the adjust column
kcb_cleaned= kcb.drop(columns=["Adjust"])

In [62]:
kcb_cleaned.to_csv(r"C:\Users\Win\NSE Project\Data\2013 to 2024 CLEANED_cosolidated_KCB_stocks nse_data.csv", index=False)

#### we check and drop null values and duplicates

In [63]:
scom_cleaned.isnull().sum()

DATE         0
CODE         0
NAME         0
12m Low      0
12m High     0
Day Low      0
Day High     0
Day Price    0
Previous     0
Change       0
Change%      0
Volume       0
dtype: int64

In [64]:
scom_cleaned.duplicated().sum()

np.int64(0)

In [65]:
kcb_cleaned.isnull().sum()

DATE         0
CODE         0
NAME         0
12m Low      0
12m High     0
Day Low      0
Day High     0
Day Price    0
Previous     0
Change       0
Change%      0
Volume       0
dtype: int64

In [66]:
kcb_cleaned.duplicated().sum()

np.int64(0)

### 😊☺ ends the data collection and cleaning phase